services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: openemr
      MYSQL_USER: openemr
      MYSQL_PASSWORD: openemrpass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - ehr_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 10

  openemr:
    image: openemr/openemr:7.0.0
    container_name: openemr
    restart: always
    environment:
      OE_USER: admin
      OE_PASS: pass
      MYSQL_HOST: mariadb
      MYSQL_ROOT_PASS: rootpass
      MYSQL_USER: openemr
      MYSQL_PASS: openemrpass
      MYSQL_DATABASE: openemr
    ports:
      - "8081:80"
    volumes:
      - openemr_sites:/var/www/localhost/htdocs/openemr/sites
      - openemr_logs:/var/log
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - ehr_network
    # 🛑 NEW FIX: ADDED HEALTH CHECK TO ENSURE SCHEMA IS READY
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"] # Check for the permanent login page
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Give the setup script more time to run and delete setup.php

  ehrbridge_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ehrbridge_api
    restart: on-failure
    command: ["dotnet", "api/EhrBridge.Api.dll"]
    ports:
      - "8080:8080"
    # 🛑 DEPENDS ON OPENEMR being available for its own connectivity check logic
    depends_on:
      - openemr
    networks:
      - ehr_network
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__EhrDatabase=Server=mariadb;Database=openemr;User Id=openemr;Password=openemrpass;

  ehrbridge_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ehrbridge_worker
    restart: "no" # Set to "no" to ensure it only runs once per fresh start
    command: ["dotnet", "worker/EhrIntegrationBridge.dll"]
    environment:
      - WORKER_MODE=Sync
      - ConnectionStrings__EhrDatabase=Server=mariadb;Database=openemr;User Id=openemr;Password=openemrpass;
    networks:
      - ehr_network
    # 🛑 NEW FIX: DEPENDS ON OpenEMR being HEALTHY (i.e., table is created)
    depends_on:
      openemr:
        condition: service_healthy

networks:
  ehr_network:
    driver: bridge

volumes:
  mariadb_data:
  openemr_sites:
  openemr_logs: