version: '3.4'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: openemr
      MYSQL_USER: openemr
      MYSQL_PASSWORD: openemrpass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - ehr_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 10

  openemr:
    image: openemr/openemr:7.0.0
    container_name: openemr
    restart: always
    environment:
      OE_USER: admin
      OE_PASS: pass
      MYSQL_HOST: mariadb
      MYSQL_ROOT_PASS: rootpass
      MYSQL_USER: openemr
      MYSQL_PASS: openemrpass
      MYSQL_DATABASE: openemr
    ports:
      - "8081:80"
    volumes:
      - openemr_sites:/var/www/localhost/htdocs/openemr/sites
      - openemr_logs:/var/log
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - ehr_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  ehrbridge_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ehrbridge_api
    restart: on-failure
    # 🛑 FIX: Removed 'api/' path. The DLL is published to the container root /app.
    command: ["dotnet", "EhrBridge.Api.dll"]
    ports:
      - "8080:8080"
    depends_on:
      - openemr
    networks:
      - ehr_network
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__EhrDatabase=Server=mariadb;Database=openemr;User Id=openemr;Password=openemrpass;

# The ehrbridge_worker service block has been removed. Its functionality (WORKER_MODE=Sync/Extract)
# is being migrated into the persistent ehrbridge_api service.

networks:
  ehr_network:
    driver: bridge

volumes:
  mariadb_data:
  openemr_sites:
  openemr_logs: