services:
  ehr-bridge-app:
    build: .
    networks:
      - ehr_network
    volumes:
      - ./output:/app/output
    
    environment:
      - WORKER_MODE=Extract #  'Sync' or 'Extract'

  openemr:
    image: openemr/openemr:7.0.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - mariadb-data:/var/lib/mysql
      - openemr-logs:/var/log
      - openemr-sites:/var/www/localhost/htdocs/openemr/sites
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASS=rootpass
      - MYSQL_USER=openemr
      - MYSQL_PASS=openemrpass
      - MYSQL_DATABASE=openemr
    networks:
      - ehr_network

  mariadb:
    image: mariadb:10.6
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=openemr
      - MYSQL_USER=openemr
      - MYSQL_PASSWORD=openemrpass
    networks:
      - ehr_network

networks:
  ehr_network:
    driver: bridge

volumes:
  mariadb-data:
  openemr-logs:
  openemr-sites: